// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtE9EgNcanm1N6da-YvBY3De2dtkCrFM4',
    appId: '1:722868091101:web:2e518796f1d09c95a40334',
    messagingSenderId: '722868091101',
    projectId: 'test-project-9d744',
    authDomain: 'test-project-9d744.firebaseapp.com',
    storageBucket: 'test-project-9d744.firebasestorage.app',
    measurementId: 'G-15JX14BN6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5yORkP8pziW5x0zXKR0dyXuv-Tgr0AEw',
    appId: '1:722868091101:android:6a1f052102747471a40334',
    messagingSenderId: '722868091101',
    projectId: 'test-project-9d744',
    storageBucket: 'test-project-9d744.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFVUhaOXj-PfNR6ZRasgbAHN7z0uSkmBE',
    appId: '1:722868091101:ios:303735eef1960010a40334',
    messagingSenderId: '722868091101',
    projectId: 'test-project-9d744',
    storageBucket: 'test-project-9d744.firebasestorage.app',
    iosBundleId: 'com.redlinetech.flutterFlowShowcase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFVUhaOXj-PfNR6ZRasgbAHN7z0uSkmBE',
    appId: '1:722868091101:ios:303735eef1960010a40334',
    messagingSenderId: '722868091101',
    projectId: 'test-project-9d744',
    storageBucket: 'test-project-9d744.firebasestorage.app',
    iosBundleId: 'com.redlinetech.flutterFlowShowcase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtE9EgNcanm1N6da-YvBY3De2dtkCrFM4',
    appId: '1:722868091101:web:f40d704ced54c674a40334',
    messagingSenderId: '722868091101',
    projectId: 'test-project-9d744',
    authDomain: 'test-project-9d744.firebaseapp.com',
    storageBucket: 'test-project-9d744.firebasestorage.app',
    measurementId: 'G-HDT545MVZ4',
  );
}
